<?php

namespace AccueilBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContributeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributeurRepository extends EntityRepository
{
}
